[versions]
ktor = "1.6.7"
junit5-jupiter = "5.2.0"
kotlinx-serialization = "1.3.2"
kotlin = "1.6.21"
dokka = "1.6.10"

[libraries]
logback-classic = "ch.qos.logback:logback-classic:1.2.10"
woodstox = "com.fasterxml.woodstox:woodstox-core:6.2.6"
kxml2 = "net.sf.kxml:kxml2:2.3.0"

ktor-serialization = { module = "io.ktor:ktor-serialization", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }

junit5-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5-jupiter" }
junit5-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5-jupiter" }

serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref="dokka" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref="kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref="kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref="kotlin" }
kotlin-js = { id = "org.jetbrains.kotlin.js", version.ref="kotlin" }
