name: Publish to GH Packages

on:
  workflow_dispatch:

permissions:
    contents: read
    packages: write

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build library
      run: ./gradlew build
    - name: Publish artifacts
      run: ./gradlew publishKotlinMultiplatformPublicationToGitHubPackagesRepository
      env:
        GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
